#! /bin/bash
FILE=/sys/devices/platform/applesmc.768/leds/smc::kbd_backlight/brightness
VAL=$(cat $FILE)

if [ "${VAL}" -gt 0 ]; then
    if [ "${VAL}" -le 10 ]; then
        echo 0 > $FILE
    else
        echo $(($VAL-10)) > $FILE
    fi 
fi
