print("Weight 1?")
w1 = float(input())
print("Weight 2?")
w2 = float(input())
print("Weight 3?")
w3 = float(input())
denom = w1 + w2 + w3
print(f"Weight 1 => {w1}/{denom} = {(w1/denom)*100}%")
print(f"Weight 2 => {w2}/{denom} = {(w2/denom)*100}%")
print(f"Weight 3 => {w3}/{denom} = {(w3/denom)*100}%")
