#! /bin/bash

# Run with no args for windows keyboard
# with argument  m for mac keyboard

if [[ $1 == 'm' ]] ; then
    sed -i s/MOD1/MOD4/g ~/.config/i3/config
else
    sed -i s/MOD4/MOD1/g ~/.config/i3/config
fi

i3-msg restart


