#! /bin/sh

# sxhkd started in .xprofile
# sxhkd & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^3' 
bspc rule -a Nemo state=floating

$HOME/.config/polybar/launch.sh

