#! /bin/sh
# Stolen From https://github.com/D630/bin/blob/master/bspwm-rules and pared down
#
# bspwm: external_rules_command
#
# Absolute path to the command used to retrieve rule consequences.
# The command will receive the following arguments: window ID, class
# name, instance name, and intermediate consequences. The output of
# that command must have the following format: key1=value1
# key2=value2 ...  (the valid key/value pairs are given in the
# description of the rule command).
#
#

border= \
    center= \
    class=$2
desktop= \
    focus= \
    follow= \
    hidden= \
    id=${1?} \
    instance=$3 \
    layer= \
    locked= \
    manage= \
    marked= \
    misc=$4 \
    monitor= \
    node= \
    private= \
    rectangle= \
    split_dir= \
    split_ratio= \
    state= \
    sticky= \
    urgent=;

spotify() {
    desktop=^3;
}

case $instance.$class in
    (*.Spotify) spotify;;
    (.)
        case $(ps -p "$(xdo pid "$id")" -o comm= 2>/dev/null) in
            (spotify) spotify;;
        esac;;
esac;



echo \
    ${desktop:+"desktop=$desktop"} \
