alias ls='ls --color=auto -A'
alias ei3='vim ~/.config/i3/config'
alias epb='vim ~/.config/polybar/config'
alias exg='vim /etc/X11/xorg.conf.d/xorg.conf'
alias etm='vim ~/.config/termite/config'
alias ka='killall'
alias poly=''
alias "pacman -S"='sudo pacman -S'
alias "git -s"='git status'
