alias ls='ls --color=auto -A'
alias ei3='ec i3'
alias etm='ec termite'
alias epb='vim "+set syntax=dosini" ~/.config/polybar/config'
alias exg='vim /etc/X11/xorg.conf.d/xorg.conf'
alias ka='killall'
alias bt=bluetoothctl
alias zth='zathura'
alias ztf='zathura --fork'
alias jnl='journalctl'
alias ..='cd ..'
alias df='df -h'
alias du='du -h'
alias c='clear'
alias e='exit'
alias m='man'
alias pm='sudo pacman'
alias stl='sudo systemctl'


