#! /bin/bash

if [[ ! $1 ]]; then
    echo "usage: change-monitor <profile>" 
    echo "where <profile> is in ~/.screenlayout"
    exit 1
fi

layout_path=~/.screenlayout/$1.sh

if [[ ! -f $layout_path ]]; then
    echo "enter valid profile, from ~/.screenlayout"
    exit 1
fi

# Change layout
$layout_path

# Postswitch
feh --bg-scale --randomize ~/backgrounds &
~/.config/polybar/launch.sh


