#! /bin/bash
FILE=/sys/devices/platform/applesmc.768/leds/smc::kbd_backlight/brightness
VAL=$(cat $FILE)

if [ "${VAL}" -lt 255 ]; then
    if [ "${VAL}" -ge 245 ]; then
        echo 255 > $FILE
    else
        echo $(($VAL+10)) > $FILE
    fi 
    fi
